1. Imprime la versión de numpy

In [1]:
import numpy as np

2. Cree un vector nulo de tamaño 10

In [7]:
n = np.zeros(10)
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. ¿Cómo obtener la documentación de la función zeros de numpy desde la línea de comandos?

In [ ]:
# python -m pydoc numpy.zeros

4. Cree un vector con valores ordenados del 10 al 49

In [9]:
c = np.arange(10, 49)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


5. Invierte el orden un vector

In [11]:
n = c.copy()
m = n[::-1]
print(m)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


6. Cree una matriz 3x3 con valores que vayan del 0 al 8

In [19]:
matriz = np.arange(0, 9).reshape(3, 3)
### La regla para reshape es que el range coincida con el valor de reshape a x b
print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Encuentre los índices de los elementos distintos de cero en [1,2,0,0,4,0]

In [23]:
lista = [1, 2, 0, 0, 4, 0]
lista_posiciones = []
posicion = 0

for i in range(len(lista)):
    if lista[posicion] != 0:
        lista_posiciones.append(posicion)
        posicion += 1
    else:
        posicion += 1
print(lista_posiciones)





[0, 1, 4]


8. Cree una matriz de identidad 3x3

In [31]:
matrizovich = np.eye(3)
matrizovich2 = np.identity(3)
print(matrizovich)
print(matrizovich2)
print(matrizovich == matrizovich2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


9.  Cree un array 10x10 con valores aleatorios y encuentre los valores mínimo y máximo

In [2]:
import numpy as np

array = np.random.randint(0, 100,(10, 10))
print(array)

minn = array[0, 0]
maxx = array[0, 0]

for fila in array:
    for x in fila:
        if x > maxx:
            maxx = x
        if x < minn:
            minn = x
print(maxx, minn)

[[ 1 67 10 32 66 76 70 42 32 38]
 [19 95 46 77 49 31 14 47 75 93]
 [82 38 74 54 18 70 95  6 16 80]
 [91 51 52 63  5 55 69 12 64 51]
 [61 19 84 40 86  7 55 19 88 36]
 [23 32 65 15 60 12 38 66 49 67]
 [93 83 29 46 36 27 59 53  7 30]
 [25 77 11 46 41 55 47 95 20 53]
 [29 79 30  0 80  4 20 11 84  5]
 [96 12 94 22  1 66 14 38  8 32]]
96 0
